# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d7c6c8ccaa4e2976173ee7992abf0164a4712a37ffe365357271f5a4c0b14693828c8b2811c7dc71209f6ef91fb1631aa114b712412878d6aa9203a75a2049

test:
  secret_key_base: 1bc120fd66fdaac3ace9241c328dce4ff72564229730ea3d1cdeb69ae2dc4e8b1cf78fca5ebcba9e151bdf68e56b062fa63bf772e95884c2b4e452c9710791af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
